on:
  push:
    branches:
    - main
    - release/*
  
  workflow_dispatch:
    
jobs:
  deploy:
    name: deploy react app
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout repositoty
      uses: actions/checkout@v3
    - name: Set up node versin 14
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run unit tests
      run: npm test
    - name: Build code
      run: npm run build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    - name: Upload to S3 bucket
      run: aws s3 sync /build s3://react-app-deployment
