name: Deploy using Dockerfile

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Details
        run: |
          echo "Current branch is ${{ github.ref }}"
          echo "File version is 1.0"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t react-app-docker-deploy .
